### ISSUE TITLE
gulp-uglify-es - makes gulp fail

### ISSUE THREAD

**Issue by viegelinsch** [hzi-braunschweig/gophish#128]
Context: Trying to build the docker image
Challenge: gulp requires a lot of heap space (> 10 GB) at the moment

When running "gulp" on this project after some while the following error appears:
```
SyntaxError in plugin "gulp-uglify-es"
Message:
Private field must be used in an enclosing class
Details:
filename: vendor.min.js
line: 1214691
col: 0
pos: 79561741
domainEmitter: [object Object]
domainThrown: false
```

Please see if you can fix this.

**Comment by qy-zh** [comment]
The RUN gulp command triggers the vendorjs function, which regenerates the vendor.min.js file. However, this step is unnecessary as the components within vendor.min.js remain static.
